wandb_version: 1

_name:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
    start_time: 1655813585
    t:
      1:
      - 1
      - 50
      - 55
      - 64
      3:
      - 24
      4: 3.6.10
      5: 0.12.18
      8:
      - 5
args:
  desc: null
  value:
    _name: transformer
    activation_dropout: 0.3
    activation_fn: relu
    adam_betas:
    - 0.9
    - 0.999
    adam_eps: 1.0e-08
    adaptive_input: false
    adaptive_softmax_cutoff: null
    adaptive_softmax_dropout: 0
    aim_repo: null
    aim_run_hash: null
    all_gather_list_size: 16384
    amp: false
    amp_batch_retries: 2
    amp_init_scale: 128
    amp_scale_window: null
    arch: transformer
    attention_dropout: 0.0
    azureml_logging: false
    batch_size: 32
    batch_size_valid: 32
    best_checkpoint_metric: loss
    bf16: false
    bpe: null
    broadcast_buffers: false
    bucket_cap_mb: 25
    checkpoint_activations: false
    checkpoint_shard_count: 1
    checkpoint_suffix: ''
    clip_norm: 0.0
    combine_valid_subsets: null
    continue_once: null
    cpu: false
    cpu_offload: false
    criterion: label_smoothed_cross_entropy
    cross_self_attention: false
    curriculum: 0
    data: /home/VD/cychang/ironside_nmt/BPE_METHOD/pcm_en.tokenized.pcm-en
    data_buffer_size: 10
    dataset_impl: null
    ddp_backend: no_c10d
    ddp_comm_hook: none
    decoder_attention_heads: 10
    decoder_embed_dim: 300
    decoder_embed_path: null
    decoder_ffn_embed_dim: 1024
    decoder_input_dim: 300
    decoder_layerdrop: 0.1
    decoder_layers: 4
    decoder_layers_to_keep: null
    decoder_learned_pos: true
    decoder_normalize_before: false
    decoder_output_dim: 300
    device_id: 0
    disable_validation: false
    distributed_backend: nccl
    distributed_init_method: null
    distributed_no_spawn: false
    distributed_num_procs: 8
    distributed_port: -1
    distributed_rank: 0
    distributed_world_size: 8
    dropout: 0.3
    ema_decay: 0.9999
    ema_fp32: false
    ema_seed_model: null
    ema_start_update: 0
    ema_update_freq: 1
    empty_cache_freq: 0
    encoder_attention_heads: 10
    encoder_embed_dim: 300
    encoder_embed_path: null
    encoder_ffn_embed_dim: 1024
    encoder_layerdrop: 0.0
    encoder_layers: 4
    encoder_layers_to_keep: null
    encoder_learned_pos: true
    encoder_normalize_before: false
    eos: 2
    eval_bleu: false
    eval_bleu_args: '{}'
    eval_bleu_detok: space
    eval_bleu_detok_args: '{}'
    eval_bleu_print_samples: false
    eval_bleu_remove_bpe: null
    eval_tokenized_bleu: false
    fast_stat_sync: false
    find_unused_parameters: true
    finetune_from_model: null
    fix_batches_to_gpus: false
    fixed_validation_seed: null
    fp16: false
    fp16_adam_stats: false
    fp16_init_scale: 128
    fp16_no_flatten_grads: false
    fp16_scale_tolerance: 0.0
    fp16_scale_window: null
    fp32_reduce_scatter: false
    gen_subset: test
    gradient_as_bucket_view: false
    grouped_shuffling: false
    heartbeat_timeout: -1
    ignore_prefix_size: 0
    ignore_unused_valid_subsets: false
    keep_best_checkpoints: -1
    keep_interval_updates: -1
    keep_interval_updates_pattern: -1
    keep_last_epochs: -1
    label_smoothing: 0.5
    layernorm_embedding: false
    left_pad_source: true
    left_pad_target: false
    load_alignments: false
    load_checkpoint_on_all_dp_ranks: false
    localsgd_frequency: 3
    log_file: null
    log_format: json
    log_interval: 10
    lr:
    - 0.0005
    lr_scheduler: inverse_sqrt
    max_epoch: 550
    max_source_positions: 1024
    max_target_positions: 1024
    max_tokens: null
    max_tokens_valid: null
    max_update: 0
    max_valid_steps: null
    maximize_best_checkpoint_metric: false
    memory_efficient_bf16: false
    memory_efficient_fp16: false
    min_loss_scale: 0.0001
    min_params_to_wrap: 100000000
    model_parallel_size: 1
    no_cross_attention: false
    no_epoch_checkpoints: true
    no_last_checkpoints: false
    no_progress_bar: false
    no_reshard_after_forward: false
    no_save: false
    no_save_optimizer_state: false
    no_scale_embedding: false
    no_seed_provided: false
    no_token_positional_embeddings: false
    not_fsdp_flatten_parameters: false
    nprocs_per_node: 8
    num_batch_buckets: 0
    num_shards: 1
    num_workers: 1
    offload_activations: false
    on_cpu_convert_precision: false
    optimizer: adam
    optimizer_overrides: '{}'
    pad: 1
    patience: -1
    pipeline_balance: null
    pipeline_checkpoint: never
    pipeline_chunks: 0
    pipeline_decoder_balance: null
    pipeline_decoder_devices: null
    pipeline_devices: null
    pipeline_encoder_balance: null
    pipeline_encoder_devices: null
    pipeline_model_parallel: false
    plasma_path: /tmp/plasma
    profile: false
    quant_noise_pq: 0
    quant_noise_pq_block_size: 8
    quant_noise_scalar: 0
    quantization_config_path: null
    report_accuracy: false
    required_batch_size_multiple: 8
    required_seq_len_multiple: 1
    reset_dataloader: false
    reset_logging: false
    reset_lr_scheduler: false
    reset_meters: false
    reset_optimizer: false
    restore_file: checkpoint_last.pt
    save_dir: /home/VD/cychang/ironside_nmt/bpe_pcm_en_300_32_1024_ffnn_checkpoints/
    save_interval: 1
    save_interval_updates: 0
    scoring: bleu
    seed: 1
    sentence_avg: false
    shard_id: 0
    share_all_embeddings: false
    share_decoder_input_output_embed: false
    simul_type: null
    skip_invalid_size_inputs_valid_test: false
    skip_remainder_batch: false
    slowmo_base_algorithm: localsgd
    slowmo_momentum: null
    source_lang: pcm
    stop_min_lr: -1.0
    stop_time_hours: 0
    store_ema: false
    suppress_crashes: false
    target_lang: en
    task: translation
    tensorboard_logdir: null
    threshold_loss_scale: null
    tie_adaptive_weights: false
    tokenizer: null
    tpu: false
    train_subset: train
    truncate_source: false
    unk: 3
    update_epoch_batch_itr: false
    update_freq:
    - 1
    update_ordered_indices_seed: false
    upsample_primary: -1
    use_bmuf: false
    use_old_adam: false
    use_plasma_view: false
    use_sharded_state: false
    user_dir: null
    valid_subset: valid
    validate_after_updates: 0
    validate_interval: 1
    validate_interval_updates: 0
    wandb_project: Large Scale Machine PCM to EN Machine Translation
    warmup_init_lr: -1
    warmup_updates: 4000
    weight_decay: 0.0
    write_checkpoints_asynchronously: false
    zero_sharding: none
bmuf:
  desc: null
  value:
    _name: null
    average_sync: false
    block_lr: 1.0
    block_momentum: 0.875
    distributed_world_size: 8
    global_sync_iter: 50
    use_nbm: false
    warmup_iterations: 500
bpe:
  desc: null
  value: null
checkpoint:
  desc: null
  value:
    _name: null
    best_checkpoint_metric: loss
    checkpoint_shard_count: 1
    checkpoint_suffix: ''
    continue_once: null
    finetune_from_model: null
    keep_best_checkpoints: -1
    keep_interval_updates: -1
    keep_interval_updates_pattern: -1
    keep_last_epochs: -1
    load_checkpoint_on_all_dp_ranks: false
    maximize_best_checkpoint_metric: false
    model_parallel_size: 1
    no_epoch_checkpoints: true
    no_last_checkpoints: false
    no_save: false
    no_save_optimizer_state: false
    optimizer_overrides: '{}'
    patience: -1
    reset_dataloader: false
    reset_lr_scheduler: false
    reset_meters: false
    reset_optimizer: false
    restore_file: checkpoint_last.pt
    save_dir: /home/VD/cychang/ironside_nmt/bpe_pcm_en_300_32_1024_ffnn_checkpoints/
    save_interval: 1
    save_interval_updates: 0
    write_checkpoints_asynchronously: false
common:
  desc: null
  value:
    _name: null
    aim_repo: null
    aim_run_hash: null
    all_gather_list_size: 16384
    amp: false
    amp_batch_retries: 2
    amp_init_scale: 128
    amp_scale_window: null
    azureml_logging: false
    bf16: false
    cpu: false
    empty_cache_freq: 0
    fp16: false
    fp16_init_scale: 128
    fp16_no_flatten_grads: false
    fp16_scale_tolerance: 0.0
    fp16_scale_window: null
    log_file: null
    log_format: json
    log_interval: 10
    memory_efficient_bf16: false
    memory_efficient_fp16: false
    min_loss_scale: 0.0001
    model_parallel_size: 1
    no_progress_bar: false
    on_cpu_convert_precision: false
    plasma_path: /tmp/plasma
    profile: false
    quantization_config_path: null
    reset_logging: false
    seed: 1
    suppress_crashes: false
    tensorboard_logdir: null
    threshold_loss_scale: null
    tpu: false
    use_plasma_view: false
    user_dir: null
    wandb_project: Large Scale Machine PCM to EN Machine Translation
common_eval:
  desc: null
  value:
    _name: null
    model_overrides: '{}'
    path: null
    post_process: null
    quiet: false
    results_path: null
criterion:
  desc: null
  value:
    _name: label_smoothed_cross_entropy
    ignore_prefix_size: 0
    label_smoothing: 0.5
    report_accuracy: false
    sentence_avg: false
dataset:
  desc: null
  value:
    _name: null
    batch_size: 32
    batch_size_valid: 32
    combine_valid_subsets: null
    curriculum: 0
    data_buffer_size: 10
    dataset_impl: null
    disable_validation: false
    fixed_validation_seed: null
    gen_subset: test
    grouped_shuffling: false
    ignore_unused_valid_subsets: false
    max_tokens: null
    max_tokens_valid: null
    max_valid_steps: null
    num_shards: 1
    num_workers: 1
    required_batch_size_multiple: 8
    required_seq_len_multiple: 1
    shard_id: 0
    skip_invalid_size_inputs_valid_test: false
    train_subset: train
    update_epoch_batch_itr: false
    update_ordered_indices_seed: false
    valid_subset: valid
    validate_after_updates: 0
    validate_interval: 1
    validate_interval_updates: 0
distributed_training:
  desc: null
  value:
    _name: null
    broadcast_buffers: false
    bucket_cap_mb: 25
    cpu_offload: false
    ddp_backend: no_c10d
    ddp_comm_hook: none
    device_id: 0
    distributed_backend: nccl
    distributed_init_method: tcp://localhost:14786
    distributed_no_spawn: false
    distributed_num_procs: 8
    distributed_port: -1
    distributed_rank: 0
    distributed_world_size: 8
    fast_stat_sync: false
    find_unused_parameters: true
    fix_batches_to_gpus: false
    fp16: false
    fp32_reduce_scatter: false
    gradient_as_bucket_view: false
    heartbeat_timeout: -1
    localsgd_frequency: 3
    memory_efficient_fp16: false
    no_reshard_after_forward: false
    not_fsdp_flatten_parameters: false
    nprocs_per_node: 8
    pipeline_balance: null
    pipeline_checkpoint: never
    pipeline_chunks: 0
    pipeline_decoder_balance: null
    pipeline_decoder_devices: null
    pipeline_devices: null
    pipeline_encoder_balance: null
    pipeline_encoder_devices: null
    pipeline_model_parallel: false
    slowmo_base_algorithm: localsgd
    slowmo_momentum: null
    tpu: false
    use_sharded_state: false
    zero_sharding: none
ema:
  desc: null
  value:
    _name: null
    ema_decay: 0.9999
    ema_fp32: false
    ema_seed_model: null
    ema_start_update: 0
    ema_update_freq: 1
    store_ema: false
eval_lm:
  desc: null
  value:
    _name: null
    context_window: 0
    output_word_probs: false
    output_word_stats: false
    softmax_batch: 9223372036854775807
generation:
  desc: null
  value:
    _name: null
    beam: 5
    constraints: null
    decoding_format: null
    diverse_beam_groups: -1
    diverse_beam_strength: 0.5
    diversity_rate: -1.0
    eos_token: null
    iter_decode_eos_penalty: 0.0
    iter_decode_force_max_iter: false
    iter_decode_max_iter: 10
    iter_decode_with_beam: 1
    iter_decode_with_external_reranker: false
    lenpen: 1.0
    lm_path: null
    lm_weight: 0.0
    match_source_len: false
    max_len_a: 0.0
    max_len_b: 200
    min_len: 1
    nbest: 1
    no_beamable_mm: false
    no_early_stop: false
    no_repeat_ngram_size: 0
    no_seed_provided: false
    prefix_size: 0
    print_alignment: null
    print_step: false
    replace_unk: null
    retain_dropout: false
    retain_dropout_modules: null
    retain_iter_history: false
    sacrebleu: false
    sampling: false
    sampling_topk: -1
    sampling_topp: -1.0
    score_reference: false
    temperature: 1.0
    unkpen: 0.0
    unnormalized: false
interactive:
  desc: null
  value:
    _name: null
    buffer_size: 0
    input: '-'
lr_scheduler:
  desc: null
  value:
    _name: inverse_sqrt
    lr:
    - 0.0005
    warmup_init_lr: -1.0
    warmup_updates: 4000
optimization:
  desc: null
  value:
    _name: null
    clip_norm: 0.0
    lr:
    - 0.0005
    max_epoch: 550
    max_update: 0
    sentence_avg: false
    skip_remainder_batch: false
    stop_min_lr: -1.0
    stop_time_hours: 0.0
    update_freq:
    - 1
    use_bmuf: false
optimizer:
  desc: null
  value:
    _name: adam
    adam_betas:
    - 0.9
    - 0.999
    adam_eps: 1.0e-08
    fp16_adam_stats: false
    lr:
    - 0.0005
    tpu: false
    use_old_adam: false
    weight_decay: 0.0
scoring:
  desc: null
  value:
    _name: bleu
    eos: 2
    pad: 1
    unk: 3
simul_type:
  desc: null
  value: null
task:
  desc: null
  value:
    _name: translation
    data: /home/VD/cychang/ironside_nmt/BPE_METHOD/pcm_en.tokenized.pcm-en
    dataset_impl: null
    eval_bleu: false
    eval_bleu_args: '{}'
    eval_bleu_detok: space
    eval_bleu_detok_args: '{}'
    eval_bleu_print_samples: false
    eval_bleu_remove_bpe: null
    eval_tokenized_bleu: false
    left_pad_source: true
    left_pad_target: false
    load_alignments: false
    max_source_positions: 1024
    max_target_positions: 1024
    num_batch_buckets: 0
    required_seq_len_multiple: 1
    source_lang: pcm
    target_lang: en
    train_subset: train
    truncate_source: false
    upsample_primary: -1
tokenizer:
  desc: null
  value: null
